In [2]:
import numpy as np

In [10]:
data = np.array([1, 1, 2, 3, 3, 3,3 ,5, 3, 3,3 ,3, 9, 10, 10, 3])
data

array([ 1,  1,  2,  3,  3,  3,  3,  5,  3,  3,  3,  3,  9, 10, 10,  3])

In [16]:
data = data.reshape([-1, 4])
data

array([[ 1,  1,  2,  3],
       [ 3,  3,  3,  5],
       [ 3,  3,  3,  3],
       [ 9, 10, 10,  3]])

In [17]:
data = data.T
data

array([[ 1,  3,  3,  9],
       [ 1,  3,  3, 10],
       [ 2,  3,  3, 10],
       [ 3,  5,  3,  3]])